# https://www.serverless.com/blog/cors-api-gateway-survival-guide/
service: moon-phase-server
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  httpApi:
    cors: true

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
# service: products-service

# provider:
#   name: aws
#   runtime: nodejs6.10

# functions:
#   getProduct:
#     handler: handler.getProduct
#     events:
#       - http:
#           path: product/{id}
#           method: get
#           cors: true # <-- CORS!
#   createProduct:
#     handler: handler.createProduct
#     events:
#       - http:
#           path: product
#           method: post
#           cors: true # <-- CORS!
